services:
  backend:
    image: kishorek123/monai:backend-gpu
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: monai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
    environment:
      - CKPT_PATH=/app/outputs/checkpoints/best_cxr_multilabel_13.pt
      - VAL_LOADER_PATH=/app/outputs/val_samples_1.pkl
      - TEMP_DIR=/app/static/heatmaps
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  frontend:
    image: kishorek123/monai:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: monai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
